"use client";

import type { Client, Post, PostStatus } from "@/types";
import { STATUSES } from "@/types";

const colors: Record<PostStatus, string> = { Ideia: "#EAEAE5", Roteiro: "#E7F1FF", Arte: "#FFF1D6", Aprovação: "#F2E8FF", Agendado: "#DFF4EE", Publicado: "#E8F6CF" };

export function BoardView({ posts, clients, onOpen, onStatusChange }: { posts: Post[]; clients: Client[]; onOpen: (post: Post) => void; onStatusChange: (post: Post, status: PostStatus) => Promise<void> }) {
  return <div><div className="mb-7"><p className="mb-1 text-sm font-semibold text-[#7A7A73]">Arraste no computador ou altere no celular</p><h1 className="font-display text-3xl font-extrabold sm:text-4xl">Quadro por status</h1></div><div className="scrollbar-none flex snap-x gap-4 overflow-x-auto pb-5">{STATUSES.map((status) => { const items = posts.filter((post) => post.status === status); return <section key={status} className="w-[82vw] max-w-80 shrink-0 snap-start rounded-3xl p-3" style={{ background: colors[status] }} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { const post = posts.find((item) => item.id === event.dataTransfer.getData("postId")); if (post && post.status !== status) void onStatusChange(post, status); }}><div className="mb-3 flex items-center justify-between px-1"><h2 className="font-display font-extrabold">{status}</h2><span className="rounded-full bg-white/70 px-2 py-1 text-xs font-bold">{items.length}</span></div><div className="space-y-2">{items.map((post) => <article key={post.id} draggable onDragStart={(event) => event.dataTransfer.setData("postId", post.id)} className="rounded-2xl bg-white p-4 shadow-sm"><button onClick={() => onOpen(post)} className="w-full text-left"><div className="mb-2 flex items-center gap-2 text-[11px] font-semibold text-[#77776F]"><span className="size-2 rounded-full" style={{ background: clients.find((client) => client.id === post.client_id)?.color || "#aaa" }} />{clients.find((client) => client.id === post.client_id)?.name}</div><h3 className="font-display text-sm font-extrabold">{post.title}</h3><p className="mt-2 text-xs text-[#77776F]">{post.planned_date || "Sem data"}</p></button><select aria-label={`Status de ${post.title}`} className="mt-3 h-9 w-full rounded-lg border border-[#DEDED8] bg-white px-2 text-xs sm:hidden" value={post.status} onChange={(event) => void onStatusChange(post, event.target.value as PostStatus)}>{STATUSES.map((option) => <option key={option}>{option}</option>)}</select></article>)}</div></section>; })}</div></div>;
}
