"use client";

import { ChevronLeft, ChevronRight } from "lucide-react";
import { useMemo, useState } from "react";
import type { Client, Post } from "@/types";
import { Button } from "./ui";

const weekdays = ["Seg", "Ter", "Qua", "Qui", "Sex", "Sáb", "Dom"];
function key(date: Date) { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; }

export function CalendarView({ posts, clients, onOpen }: { posts: Post[]; clients: Client[]; onOpen: (post: Post) => void }) {
  const [month, setMonth] = useState(() => new Date(new Date().getFullYear(), new Date().getMonth(), 1));
  const [selected, setSelected] = useState(() => key(new Date()));
  const days = useMemo(() => { const first = new Date(month); const mondayOffset = (first.getDay() + 6) % 7; const start = new Date(first); start.setDate(first.getDate() - mondayOffset); return Array.from({ length: 42 }, (_, index) => { const date = new Date(start); date.setDate(start.getDate() + index); return date; }); }, [month]);
  const selectedPosts = posts.filter((post) => post.planned_date === selected);
  function changeMonth(value: number) { setMonth((current) => new Date(current.getFullYear(), current.getMonth() + value, 1)); }
  return <div><div className="mb-7 flex items-end justify-between"><div><p className="mb-1 text-sm font-semibold text-[#7A7A73]">Planejamento por data</p><h1 className="font-display text-3xl font-extrabold sm:text-4xl">Calendário</h1></div><div className="flex gap-2"><Button variant="secondary" className="px-3" onClick={() => changeMonth(-1)}><ChevronLeft size={18} /></Button><Button variant="secondary" className="px-3" onClick={() => changeMonth(1)}><ChevronRight size={18} /></Button></div></div><div className="mb-3 text-center font-display text-xl font-extrabold capitalize">{new Intl.DateTimeFormat("pt-BR", { month: "long", year: "numeric" }).format(month)}</div><div className="overflow-hidden rounded-3xl border border-[#E0E0DA] bg-white"><div className="grid grid-cols-7 bg-[#F0F0EB]">{weekdays.map((day) => <div key={day} className="p-2 text-center text-[11px] font-bold uppercase text-[#77776F]">{day}</div>)}</div><div className="grid grid-cols-7">{days.map((date) => { const dayKey = key(date); const items = posts.filter((post) => post.planned_date === dayKey); const currentMonth = date.getMonth() === month.getMonth(); return <button key={dayKey} onClick={() => setSelected(dayKey)} className={`min-h-20 border-r border-t border-[#ECECE7] p-1.5 text-left sm:min-h-28 sm:p-2 ${selected === dayKey ? "bg-[#F2FFD0]" : ""} ${!currentMonth ? "text-[#B5B5AE]" : ""}`}><span className="text-xs font-bold">{date.getDate()}</span><div className="mt-1 space-y-1">{items.slice(0, 2).map((post) => { const client = clients.find((item) => item.id === post.client_id); return <div key={post.id} className="truncate rounded px-1 py-0.5 text-[9px] font-bold sm:text-[10px]" style={{ background: `${client?.color || "#aaa"}25` }}>{post.title}</div>; })}{items.length > 2 && <div className="text-[9px] font-bold">+{items.length - 2}</div>}</div></button>; })}</div></div><section className="mt-6"><h2 className="font-display mb-3 text-xl font-extrabold">{new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "long" }).format(new Date(`${selected}T12:00:00`))}</h2>{!selectedPosts.length ? <p className="rounded-2xl border border-dashed border-[#CECEC7] p-5 text-sm text-[#77776F]">Nenhuma postagem nesta data.</p> : <div className="grid gap-3 sm:grid-cols-2">{selectedPosts.map((post) => <button key={post.id} onClick={() => onOpen(post)} className="rounded-2xl border border-[#E2E2DC] bg-white p-4 text-left"><h3 className="font-display font-extrabold">{post.title}</h3><p className="mt-2 text-xs text-[#77776F]">{clients.find((item) => item.id === post.client_id)?.name} · {post.status}</p></button>)}</div>}</section></div>;
}
