"use client";
/* eslint-disable @next/next/no-img-element */

import { ArrowLeft, Check, ChevronLeft, ChevronRight, Copy, ExternalLink, ImageIcon, LoaderCircle, Send, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import type { Client, Post } from "@/types";
import { Button } from "./ui";

function todayKey() { const date = new Date(); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; }
const platformUrl: Record<string, string> = { Instagram: "https://www.instagram.com/", TikTok: "https://www.tiktok.com/", "YouTube Shorts": "https://studio.youtube.com/", Facebook: "https://www.facebook.com/", LinkedIn: "https://www.linkedin.com/feed/" };

export function PublicationMode({ posts, clients, onClose, onPublish }: { posts: Post[]; clients: Client[]; onClose: () => void; onPublish: (post: Post) => Promise<void> }) {
  const queue = useMemo(() => posts.filter((post) => post.planned_date && post.planned_date <= todayKey()).sort((a, b) => a.planned_date.localeCompare(b.planned_date)), [posts]);
  const [index, setIndex] = useState(0); const [copied, setCopied] = useState(false); const [sharing, setSharing] = useState(false); const [publishing, setPublishing] = useState(false);
  useEffect(() => { if (index >= queue.length && queue.length) setIndex(queue.length - 1); }, [index, queue.length]);
  const post = queue[index];
  async function imageFiles() { return Promise.all((post?.images || []).map(async (image, itemIndex) => { const response = await fetch(image.url); if (!response.ok) throw new Error("Não foi possível carregar uma das imagens."); const blob = await response.blob(); return new File([blob], image.name || `${itemIndex + 1}-arte.png`, { type: blob.type || "image/png" }); })); }
  async function share() { if (!post?.images.length) return; setSharing(true); try { const files = await imageFiles(); if (navigator.canShare?.({ files })) await navigator.share({ files }); else { for (const file of files) { const url = URL.createObjectURL(file); const link = document.createElement("a"); link.href = url; link.download = file.name; link.click(); URL.revokeObjectURL(url); } } } catch (error) { if (!(error instanceof DOMException && error.name === "AbortError")) alert(error instanceof Error ? error.message : "Não foi possível compartilhar."); } finally { setSharing(false); } }
  async function copyCaption() { if (!post?.caption) return; await navigator.clipboard.writeText(post.caption); setCopied(true); setTimeout(() => setCopied(false), 1500); }
  async function publish() { if (!post) return; setPublishing(true); try { await onPublish(post); } finally { setPublishing(false); } }
  if (!post) return <div className="fixed inset-0 z-[60] grid place-items-center bg-[#F7F7F4] p-5"><button onClick={onClose} className="absolute left-5 top-5 flex items-center gap-2 font-semibold"><ArrowLeft size={19} />Voltar</button><div className="max-w-sm text-center"><div className="mx-auto mb-4 grid size-16 place-items-center rounded-3xl bg-[#E8F6CF]"><Check size={28} /></div><h1 className="font-display text-2xl font-extrabold">Fila concluída</h1><p className="mt-2 text-sm text-[#77776F]">Não há posts atrasados ou planejados para hoje.</p><Button className="mt-5" onClick={onClose}>Fechar</Button></div></div>;
  const client = clients.find((item) => item.id === post.client_id);
  return <div className="fixed inset-0 z-[60] overflow-y-auto bg-[#F7F7F4]"><header className="sticky top-0 z-10 flex items-center justify-between border-b border-[#E1E1DB] bg-[#F7F7F4]/95 px-4 py-3 backdrop-blur sm:px-8"><button onClick={onClose} className="flex items-center gap-2 text-sm font-semibold"><X size={19} />Sair do modo</button><span className="rounded-full bg-[#1D1D1B] px-3 py-1 text-xs font-bold text-white">{index + 1} de {queue.length}</span></header><main className="mx-auto max-w-3xl px-4 py-6 pb-28 sm:px-8"><div className="mb-5"><p className="text-xs font-bold uppercase tracking-wider text-[#77776F]"><span style={{ color: client?.color }}>●</span> {client?.name} · {post.platform}</p><h1 className="font-display mt-2 text-3xl font-extrabold">{post.title}</h1><p className="mt-2 text-sm text-[#77776F]">Planejado para {post.planned_date}</p></div>{post.images.length ? <div className="scrollbar-none mb-5 flex snap-x gap-3 overflow-x-auto">{post.images.map((image) => <img key={image.id} src={image.url} alt={image.name} className="aspect-square w-[78vw] max-w-sm shrink-0 snap-center rounded-3xl object-cover" />)}</div> : <div className="mb-5 flex min-h-40 items-center justify-center gap-2 rounded-3xl border border-dashed border-[#CECEC7] text-sm text-[#77776F]"><ImageIcon size={20} />Sem imagens</div>}<div className="mb-5 grid grid-cols-2 gap-2"><Button variant="secondary" onClick={share} disabled={sharing || !post.images.length}>{sharing ? <LoaderCircle className="animate-spin" size={17} /> : <Send size={17} />}Enviar imagens</Button><Button variant="secondary" onClick={copyCaption} disabled={!post.caption}>{copied ? <Check size={17} /> : <Copy size={17} />}{copied ? "Copiada" : "Copiar legenda"}</Button><a href={platformUrl[post.platform] || "#"} target="_blank" className="col-span-2 flex h-11 items-center justify-center gap-2 rounded-xl bg-white text-sm font-semibold border border-[#DEDED8]"><ExternalLink size={17} />Abrir {post.platform}</a></div><section className="mb-5 rounded-2xl border border-[#E2E2DC] bg-white p-5"><h2 className="text-xs font-bold uppercase tracking-wider text-[#77776F]">Legenda</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-6">{post.caption || "—"}</p></section><Button onClick={publish} disabled={publishing} className="h-14 w-full text-base">{publishing ? <LoaderCircle className="animate-spin" size={20} /> : <Check size={20} />}Marcar como publicado e avançar</Button><div className="mt-4 flex justify-between"><Button variant="ghost" onClick={() => setIndex(Math.max(0, index - 1))} disabled={index === 0}><ChevronLeft size={18} />Anterior</Button><Button variant="ghost" onClick={() => setIndex(Math.min(queue.length - 1, index + 1))} disabled={index >= queue.length - 1}>Próximo<ChevronRight size={18} /></Button></div></main></div>;
}
